# Generated by Django 4.1.4 on 2022-12-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja_app', '0002_alter_fads_decade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fads',
            new_name='Fad',
        ),
    ]
