# Generated by Django 4.1.4 on 2022-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no title', max_length=100)),
                ('image_url', models.CharField(default='no title', max_length=100)),
                ('description', models.CharField(default='no title', max_length=100)),
                ('decade', models.CharField(default='no title', max_length=100)),
            ],
        ),
    ]
