# Generated by Django 4.1.4 on 2022-12-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.TextField(null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decade', to='nostaldja.decade')),
            ],
        ),
    ]
