# Generated by Django 4.1.4 on 2022-12-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fads',
            new_name='Fad',
        ),
    ]
