# Generated by Django 4.1.4 on 2022-12-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decade',
            name='end_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='decade',
            name='start_year',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Fad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fads', to='nostaldja.decade')),
            ],
        ),
    ]
