# Generated by Django 4.1.4 on 2022-12-15 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fads',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fads',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='fads',
            name='name',
        ),
        migrations.AlterField(
            model_name='fads',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fads', to='nostaldja.decade', default="changeme"),

        ),
    ]
