# Generated by Django 4.1.4 on 2022-12-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fad',
            old_name='description',
            new_name='description_of_it',
        ),
        migrations.AlterField(
            model_name='fad',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fad', to='nostaldja.decade'),
        ),
        migrations.AlterField(
            model_name='fad',
            name='name',
            field=models.CharField(default='nope', max_length=100),
        ),
    ]
