# Generated by Django 4.1.4 on 2022-12-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_remove_fads_description_remove_fads_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fads',
            name='description',
            field=models.CharField(default='placeholderhere', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fads',
            name='image_url',
            field=models.CharField(default='changeme', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fads',
            name='name',
            field=models.CharField(default='placeholderhere', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fads',
            name='decade',
            field=models.CharField(max_length=100),
        ),
    ]
