# Generated by Django 4.1.4 on 2022-12-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_fads_description_fads_image_url_fads_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fads',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fads', to='nostaldja.decade'),
        ),
    ]
