# Generated by Django 4.1.4 on 2022-12-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fad',
            name='name',
        ),
        migrations.AddField(
            model_name='fad',
            name='fad',
            field=models.CharField(default='fad', max_length=100),
        ),
        migrations.AlterField(
            model_name='decade',
            name='end_year',
            field=models.CharField(default='end year', max_length=5),
        ),
        migrations.AlterField(
            model_name='decade',
            name='start_year',
            field=models.CharField(default='start year', max_length=5),
        ),
        migrations.AlterField(
            model_name='fad',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decade', to='tunr.decade'),
        ),
        migrations.AlterField(
            model_name='fad',
            name='description',
            field=models.TextField(default='description', max_length=300),
        ),
        migrations.AlterField(
            model_name='fad',
            name='image_url',
            field=models.CharField(default='fad photo', max_length=100),
        ),
    ]
